linters:
  # see also https://golangci-lint.run/usage/linters/#enabled-by-default
  enable:
   - gofmt
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosimple
        - staticcheck
        - ineffassign
